UsedCarShowroom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vehicles.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vehicles/urls.py
from django.urls import path
from .views import *
from . import views


urlpatterns = [
    # path('usedcarss/',VehicleListView.as_view(),name = 'usedcarpage'),
    path('', views.homePage, name='homepage'),
    path('UsedCars/', views.usedCarsPage, name='usedcarspage'),
    path('CarDetails/<int:veh_id>/', views.usedCarDetailPage, name='usedcarsdetailspage'),
    path('UsedVans/', views.usedVansPage, name='usedvanspage'),
    path('Valeting/', views.valetingPage, name='valetingpage'),
    path('AutoShine/', views.autoShinePage, name='autoshinepage'),
    path('ContactUs/', views.contactUsPage, name='contactpage'),
    path('sendMessage/', sendMessage, name='sendMessage'),
    path('sendValetEnquiry/', sendValetEnquiry, name='sendValetEnquiry'),
]

vehicles/models.py
from django.db import models
import datetime


# Create your models here.
class Vehicle(models.Model):
    TRANSMISSION = (
		('Manual','Manual'),
		('Automatic','Automatic'),
		('Continuously variable','Continuously variable'),
		('Semi-automatic and dual-clutch','Semi-automatic and dual-clutch'),
		)
    FUELTYPE = (
        ('Petrol','Petrol'),
        ('Diesel','Diesel'),
        ('Bio-Diesel','Bio-Diesel'),
        ('Compressed Natural Gas (CNG)','Compressed Natural Gas (CNG)'),
    )
    name = models.CharField(max_length=40,null=False,default='No details available', help_text='Toyota yaris')
    short_description = models.TextField(max_length=500,default='No details available')
    long_description = models.TextField(max_length=900, default='No details available')
    price = models.CharField(max_length=255,null=False,default='No details available',help_text='')
    model_year = models.IntegerField(null=False,default='No details available', help_text='2017')
    fuel_type = models.CharField(max_length=40,default='No details available',null=False,choices=FUELTYPE)
    mileage = models.CharField(max_length=255,null=False,default='No details available',help_text='21,000')
    transmission = models.CharField(max_length=40,null=False,choices=TRANSMISSION,default='No details available')
    engine_size = models.CharField(max_length=40,null=False,default='No details available',help_text='2.7L')
    color = models.CharField(max_length=40,null=False)
    listed_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(null=True,blank=True,upload_to="images/")


    def __str__(self):
    	return str(self.name)

class VehicleImage(models.Model):
	vehicle = models.ForeignKey(Vehicle, default=None, on_delete=models.CASCADE)
	image = models.ImageField(upload_to="images/")

	def __str__(self):
		return self.vehicle.name

class VehicleSummary(models.Model):
	vehicle = models.ForeignKey(Vehicle, default=None, on_delete=models.CASCADE)
	body_style = models.CharField(max_length=255, default='No details available',help_text='Hatchback')
	engine_size	= models.CharField(max_length=255, default='No details available', help_text='1299 cc')
	fuel_type =	models.CharField(max_length=255, default='No details available',help_text='Petrol')
	number_of_doors	= models.IntegerField( default='No details available',help_text='5 doors')
	number_of_seats	= models.IntegerField( default='No details available',help_text='5 seats')
	gearbox_type = models.CharField(max_length=255, default='No details available', help_text='semi-automatic')
	CO2_emissions = models.CharField(max_length=255, default='No details available', help_text='136 g/km')
	insurance_group	= models.CharField(max_length=255, default='No details available', help_text='06E')
	standard_manufacturer_warranty_miles = models.CharField(max_length=255, default='No details available', help_text='60000 miles')
	standard_manufacturer_warranty_years = models.CharField(max_length=255, default='No details available',help_text='4 years')
	standard_paintwork_guarantee = models.CharField(max_length=255, default='No details available',help_text='3 years')


	def __str__(self):
		return self.vehicle.name

class VehiclePerformanceEconomy(models.Model):
	vehicle = models.ForeignKey(Vehicle, default=None, on_delete=models.CASCADE)
	fuel_consumption_urban = models.CharField(max_length=250, default='No details available', help_text='42.2 mpg')
	fuel_consumption_extra_urban = models.CharField(max_length=250, default='No details available', help_text='42.2 mpg')
	fuel_consumption_combined = models.CharField(max_length=250, default='No details available', help_text='42.2 mpg')
	zero_to_sixty_mph = models.CharField(max_length=250, default='No details available', help_text =' 13.1 seconds')
	top_speed = models.CharField(max_length=250, default='No details available', help_text ='106 mph')
	cylinders = models.CharField(max_length=250, default='No details available', help_text ='4')
	valves = models.CharField(max_length=250, default='No details available', help_text ='16')
	engine_power = models.CharField(max_length=250, default='No details available', help_text ='85 bhp')
	engine_torque = models.CharField(max_length=250, default='No details available', help_text ='89.25 lbs/ft')

	def __str__(self):
		return self.vehicle.name


class VehicleDimension(models.Model):
	vehicle = models.ForeignKey(Vehicle, default=None, on_delete=models.CASCADE)
	height = models.CharField(max_length=250, default='No details available', help_text='1530 mm')
	height_inclusive_of_roof_rails = models.CharField(max_length=250, default='No details available', help_text='')
	length = models.CharField(max_length=250, default='No details available', help_text='1530 mm')
	wheelbase = models.CharField(max_length=250, default='No details available', help_text='2430 mm')
	width = models.CharField(max_length=250, default='No details available', help_text='1665 mm')
	width_icluding_mirrors = models.CharField(max_length=250, default='No details available', help_text='1960 mm')
	fuel_tank_capacity = models.CharField(max_length=250, default='No details available', help_text='42 litres')
	minimum_kerb_weight = models.CharField(max_length=250, default='No details available', help_text='1010 kg') 

	def __str__(self):
		return self.vehicle.name


class VehicleInterior(models.Model):
	vehicle = models.ForeignKey(Vehicle, default=None, on_delete=models.CASCADE)
	interior = models.CharField(max_length=250,default='No details available', help_text='Air-Conditioning')

	def __str__(self):
		return self.vehicle.name

class VehicleExterior(models.Model):
	vehicle = models.ForeignKey(Vehicle, default=None, on_delete=models.CASCADE)
	exterior = models.CharField(max_length=250,default='No details available', help_text='Spare Wheel')

	def __str__(self):
		return self.vehicle.name

class VehicleSafety(models.Model):
	vehicle = models.ForeignKey(Vehicle, default=None, on_delete=models.CASCADE)
	safety =  models.CharField(max_length=250,default='No details available', help_text='Air Bag')

	def __str__(self):
		return self.vehicle.name


class VehicleInquirie(models.Model):
	vehicle = models.ForeignKey(Vehicle, default=None, on_delete=models.CASCADE)
	customer_name = models.CharField(max_length=250, default='Name', help_text='Your name')
	customer_email = models.EmailField(max_length=250)
	customer_phone = models.CharField(max_length=250, help_text='Phone')
	customer_message = models.TextField(help_text='Your message')
	inquiry_date = models.DateField(auto_now_add=True)

	def __str__(self):
		return self.customer_name + ' | ' + self.vehicle.name + ' | ' + self.customer_phone

class Message(models.Model):
	name = models.CharField(max_length=250, help_text='Your name')
	email = models.EmailField(max_length=250)
	phone = models.CharField(max_length=250,help_text='Your phone number')
	message = models.TextField(help_text='Your message')
	date = models.DateField(auto_now_add=True)

	def __str__(self):
		return self.name


class Valet(models.Model):
	name = models.CharField(max_length=250, help_text='Mini valet')
	price = models.IntegerField(help_text='Valet price')

	def __str__(self):
		return self.name


class ValetFeature(models.Model):
	valet = models.ForeignKey(Valet,default=None, on_delete=models.CASCADE)
	feature = models.CharField(max_length=250, default='No details available', help_text='Valet feature')

	def __str__(self):
		return self.valet.name

		
class ValetEnquirie(models.Model):
	valet = models.ForeignKey(Valet,default=None,on_delete=models.CASCADE)
	customer_name = models.CharField(max_length=250, default='Name', help_text='Your name')
	customer_email = models.EmailField(max_length=250)
	customer_phone = models.CharField(max_length=250, help_text='Phone')
	customer_message = models.TextField(help_text='Your message')
	inquiry_date = models.DateField(auto_now_add=True)

	def __str__(self):
		return self.customer_name + ' | ' + self.valet.name + ' | ' + self.customer_phone

vehicles/forms.py
from django import forms
from django.forms import ModelForm
from .models import *



class VehicleInquiryForm(ModelForm):
	class Meta:
		model = VehicleInquirie
		fields = '__all__'

vehicles/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
from .models import *
from django.core.paginator import Paginator
from django.core import serializers
from .forms import *
from .filters import VehicleFilter
import json
from django.views.generic import ListView

# class VehicleListView(ListView):
# 	model = Vehicle
# 	template_name = 'vehicles/UsedCars.html'

# 	def get_context_data(self,**kwargs):
# 		context = super().get_context_data(**kwargs)
# 		context["qs_json"] = json.dumps(list(Vehicle.objects.values()),default=str)
# 		return context

# Create your views here.
def homePage(request):
	vehicles = Vehicle.objects.all().order_by('-id')

	context = {
		'vehicles': vehicles,
	}
	return render(request, 'vehicles/Homepage.html',context)



def usedCarsPage(request):
	if 'q' in request.GET:
		q=request.GET['q']
		vehicles = Vehicle.objects.filter(name__icontains=q).order_by('-id')
	else:
		vehicles = Vehicle.objects.all().order_by('-id')
		
	
	vehicle_filter = VehicleFilter(request.GET,queryset=vehicles)
	vehicles = vehicle_filter.qs

	paginator = Paginator(vehicles,4)
	page_num = request.GET.get('page',1)
	vehicles = paginator.page(page_num)



	context = {
		'vehicles': vehicles,
		'vehicle_filter': vehicle_filter,
		'qs_json' : json.dumps(list(Vehicle.objects.values()),default=str)
	}
	return render(request, 'vehicles/UsedCars.html', context)

def usedCarDetailPage(request,veh_id):
	veh = Vehicle.objects.get(id=veh_id)
	if  request.headers.get('x-requested-with') == 'XMLHttpRequest': 
		name = request.POST.get('name')
		email = request.POST.get('email')
		phone = request.POST.get('phone')
		message = request.POST.get('enquirymessage')

		new_message = VehicleInquirie(vehicle=veh, customer_name=name, customer_email=email, customer_phone=phone, customer_message=message)
		new_message.save()
		
		response ={
			'name': name,
			'email': email,
			'phone': phone,
		}

		return JsonResponse(response)
	
	context = {
		'veh':veh,
	}
	return render(request,'vehicles/UsedCarDetails.html',context)


def usedVansPage(request):
	return render(request, 'vehicles/UsedVans.html')

def valetingPage(request):
	valets = Valet.objects.all()

	

	context = {
		'valets': valets,
	}
	return render(request, 'vehicles/Valeting.html',context)

def autoShinePage(request):
	return render(request, 'vehicles/AutoShine.html')

def contactUsPage(request):
	return render(request,'vehicles/Contact.html')

def sendMessage(request):
	if request.is_ajax():
		name = request.POST.get('name')
		email = request.POST.get('email')
		phone = request.POST.get('phone')
		message = request.POST.get('message')

		new_message = Message(name=name, email=email, phone=phone, message=message)
		new_message.save()
		
		response ={
			'name': name,
			'email': email,
			'phone': phone,
		}

		return JsonResponse(response)


def sendValetEnquiry(request):
	# valet = Valet.objects.get(id=valet_id)

	if request.is_ajax():
		valet_id = request.POST.get('valet_id')
		valet = Valet.objects.get(id=valet_id)
		name = request.POST.get('name')
		email = request.POST.get('email')
		phone = request.POST.get('phone')
		message = request.POST.get('valetenquirymessage')

		new_valet_enquiry = ValetEnquirie(valet=valet, customer_name=name, customer_email=email, customer_phone=phone, customer_message=message)
		new_valet_enquiry.save()
		
		response ={
			'name': name,
			'email': email,
			'phone': phone,
			'valet_id': valet_id,
		}

		return JsonResponse(response)

vehicles/templates/vehicles/AutoShine.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<div class="row" style="height:80px;background-color:black"></div>


{% endblock content %}

vehicles/templates/vehicles/Contact.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<link href="{% static '/css/Contact.css' %}" rel="stylesheet" type="text/css" />
<div class="container-fluid">
<div class="timeline">
		<div class="timeline-row">
			<div class="timeline-time">
				Contact Us
			</div>
			<div class="timeline-content">
				<i class="icon-attachment"><i style="color: white" class="fas fa-address-book"></i></i>
				<h4>Contact Us</h4>
				<p>At Used Car Showroom Ltd, we stock a range of used cars and vans at great prices.If for any reason you can't find what you're looking for in stock, please contact us and we will be happy to help you find the right car or van.</p>
				
				<div class="">
					<i style="color: white" class="fas fa-phone-alt"></i>
					<span class="badge badge-pill">07765 244907</span>
					<span class="badge badge-pill">0121 5724898</span>
				</div>
			</div>
		</div>

		<div class="timeline-row">
			<div class="timeline-time">
				Where we are ?
			</div>
			<div class="timeline-content">
				<i class="icon-code"><i class="fas fa-map-marker-alt" style="color: white"></i></i>
				<h4>Used Car Showroom Ltd</h4>
				<p>
					Unit 13 CORNWALL ROAD INDUSTRIAL ESTATE, Smethwick, West Midlands, B66 2JT
				</p>
			</div>
		</div>

		<div class="timeline-row">
			<div class="timeline-time">
				Find Us<small>Get direction to our showroom</small>
			</div>
			<div class="map-responsive mr-4">
               <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2428.885745965689!2d-1.9586771847561901!3d52.49930774551582!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487097db7ad8f479%3A0x73897c614ccb003e!2sUsed%20Car%20Showroom%20Ltd!5e0!3m2!1sen!2s!4v1626097892987!5m2!1sen!2s" width="600" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
            </div>
		</div>

		<div class="timeline-row">
			<div class="timeline-time">
				Get in touch<small>Online or call us on</small>
			</div>
			<div class="timeline-content">
				<i class="icon-directions"><i style="color: white" class="fas fa-phone-alt"></i></i>
				<h4>07765 244907 | 0121 5724898</h4>
				<a class="btn btn-warning"><i class="fas fa-envelope mr-2"></i> Send us email</a>
			</div>
		</div>

		<div class="timeline-row">
			<div class="timeline-time">
				Opening Times<small>week days</small>
			</div>
			<div class="timeline-content">
				<i class="icon-change_history"><i class="far fa-calendar-alt" style="color: white"></i></i>
				<table class="table" style="color: white">
                  <tbody>
                    
                    <tr>
                      <td>Monday</td>
                      <td>Appointment Only</td>
                    </tr>
                    <tr>
                      <td>Tuesday</td>
                      <td>Appointment Only</td>
                    </tr>
                    <tr>
                      <td>Wednesday</td>
                      <td>Appointment Only</td>
                    </tr>
                    <tr>
                      <td>Thursday</td>
                      <td>Appointment Only</td>
                    </tr>
                    <tr>
                      <td>Friday</td>
                      <td>Appointment Only</td>
                    </tr>
                    <tr>
                      <td>Saturday</td>
                      <td>Appointment Only</td>
                    </tr>
                    <tr>
                      <td>Sunday</td>
                      <td>Closed</td>
                    </tr>
                  </tbody>
                </table>
			</div>
		</div>

		<div class="timeline-row">
			<div class="timeline-content">
				<p class="m-0">Loading...</p>
			</div>
		</div>

	</div>
</div>

{% endblock content %}

vehicles/templates/vehicles/UsedCars.html
{% extends 'main.html' %}
{% load static %}
{% load humanize %}
{% load bootstrap %}

{% block content %}
<link href="{% static '/css/UsedCars.css' %}" rel="stylesheet" type="text/css" />
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<!-- <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>



<!-- <div class="row" style="height:85px; background-color:black"></div> -->
<style>
#heroimage{
	background-image: url("/static/images/usedcarspage/showroom1.jpg");
	padding-top: 100px;
	background-size: cover;
	padding-bottom: 20px;
}
</style>
<!-- Search Section -->
	<div class="" id="heroimage">
	    <div class="row justify-content-center">
	        <div class="col-md-8">
	            <form>
	                <div class="input-group">
	                    <input id="search_here" type="text" name="q" class="form-control form-control-lg" placeholder="Search for vehicles" />
	                </div>
	                <div class="input-group-append justify-content-center">
                    	<button class="btn btn-info " type="submit" id="button-addon2">Search</button>
                    </div>
	            </form>

	        </div>
	    </div>
	    <div class="row justify-content-center mt-2">
	        <div class="col-md-8 text-white">
	            <form method="get">
	            	<div class="row">
	            		{% for field in vehicle_filter.form %}
	            		<div class="col-md-3 col-sm-4">
	            			{{field|bootstrap}}
	            		</div>
	            		{% endfor %}
	            	</div>
	                <div class="input-group-append justify-content-center">
                    	<button class="btn btn-info" type="submit" id="button-addon2">Search</button>
                    </div>
	            </form>
	        </div>
	    </div>
	</div>
<div class="container-fluid">
	
    

	<div class="row m-2" id="ads">
		{% if q %}
		<h6 class="text-muted text-center">You Searched For {{q}}</h6>
		{% endif %}
	    <!-- Category Card -->
	    {% for veh in vehicles %}
	    <div class="col-md-6 mt-4">
	        <div class="card rounded w-100">
	            <div class="card-image">
	                <span class="card-notify-badge">£ {{veh.price|intcomma}}</span>
	                <span class="card-notify-year">{{veh.model_year}}</span>
	                <img class="img-fluid" src="{{veh.image.url}}" alt="{{veh.name}} picture" />
	            </div>
	            <br>
	            <div class="card-image-overlay m-auto">
	                <span class="card-detail-badge">£ {{veh.price|intcomma}}</span>
	                <span class="card-detail-badge">Used</span>
	            </div>
	            <div class="card-body text-center">
	                <div class="ad-title m-auto">
	                    <h5 style="font-weight:bold">{{veh.name}}</h5>
	                </div>
	                <hr>
	                <br>
	                <h5 class="text-center">Key Facts</h5>
	                <div class="row text-center">
	          			<div class="col-sm-4">
	          				<img width=32px height=32px src="{% static 'images/usedcarspage/schedule.png'%}"/>
	          				<h6>Model Year</h6>
	          				<h6 class="font-weight-bold" style="color:crimson">{{veh.model_year}}</h6>
	          			</div>
	          			<div class="col-sm-4">
	          				<img width=32px height=32px src="{% static 'images/usedcarspage/fuel.png'%}"/>
	          				<h6 >Fuel Type</h6>
	          				<h6 class="font-weight-bold" style="color:crimson">{{veh.fuel_type}}</h6>
	          			</div>
	          			<div class="col-sm-4">
	          				<img width=32px height=32px src="{% static 'images/usedcarspage/racing.png'%}"/>
	          				<h6>Mileage</h6>
	          				<h6 class="font-weight-bold" style="color:crimson">{{veh.mileage|intcomma}}</h6>
	          			</div>
	          			<div class="col-sm-4">
	          				<img width=32px height=32px src="{% static 'images/usedcarspage/car-engine.png'%}"/>
	          				<h6>Engine Size</h6>
	          				<h6 class="font-weight-bold" style="color:crimson">{{veh.engine_size}}</h6>
	          			</div>
	          			<div class="col-sm-4">
	          				<img width=32px height=32px src="{% static 'images/usedcarspage/automatic-transmission.png'%}"/>
	          				<h6>Transmission</h6>
	          				<h6 class="font-weight-bold" style="color:crimson">{{veh.transmission}}</h6>
	          			</div>
	          			<div class="col-sm-4">
	          				<img width=32px height=32px src="{% static 'images/usedcarspage/paint-brush.png'%}"/>
	          				<h6>Color</h6>
	          				<h6 class="font-weight-bold" style="color:crimson">{{veh.color}}</h6>
	          			</div>
	          		</div>
	                <a class="ad-btn" href="{% url 'usedcarsdetailspage' veh.id %}">View Advert</a>
	            </div>
	        </div>
	    </div>
	    {% endfor %}
	</div>
	

	{% if vehicles.has_other_pages %}
	<!-- Pagination -->
	<nav class="my-3 container">
	    <ul class="pagination">
	        {% if vehicles.has_previous %}
	      <li class="page-item"><a class="page-link" href="?page={{vehicles.previous_page_number}}">Previous</a></li>
	      {% endif %}
	      {% for i in vehicles.paginator.page_range %}
	      {% if vehicles.number == i %}
	      <li class="page-item active"><a class="page-link" href="#">{{i}}</a></li>
	      {% else %}
	      <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
	      {% endif %}
	      {% endfor %}
	      {% if vehicles.has_next %}
	      <li class="page-item"><a class="page-link" href="?page={{vehicles.next_page_number}}">Next</a></li>
	      {% endif %}
	    </ul>
	</nav>
	{% endif %}
	<div class="row m-2">
		<dic class="col">
			<div class="card w-100">
				<div class="card-header bg-darkblue">
					<h5 class="card-title m-2">Used Cars for sale</h5>
				</div>
				<div class="card-body">
					<p class="card-text">
						We are confident you will not be disappointed with our selection of quality used cars. At Used Car Showroom Ltd we offer an extensive range of services and extras meaning that you can buy your used car with confidence and peace of mind. Our showroom in Smethwick stocks a wide range of cars that are ready for viewing today.
					</p>
				</div>
			</div>
		</dic>
	</div>


</div>

<div class="row m-2">
	<dic class="col">
		<div class="card w-100">
			<div class="card-header bg-dark text-white">
				<h6 class="card-title m-2"><i class="fas fa-map-marker-alt mr-2" ></i>Unit 13 CORNWALL ROAD INDUSTRIAL ESTATE, Smethwick, West Midlands, B66 2JT<span class="float-right"><i class="fas fa-phone-alt mr-2" ></i>07765 244907 | 0121 5724898</span></h6>
			</div>
		</div>
	</dic>
</div>
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>




<script type="text/javascript">
	$(function(){
		var available_veh = [
			{% for veh in vehicles %}
			"{{veh.name}}",
			{% endfor %}	
		];
		$("#id_name").autocomplete({
			source: available_veh
		});
		$("#search_here").autocomplete({
			source: available_veh
		});

	});


</script>
{% endblock content %}

vehicles/templates/vehicles/UsedVans.html
{% extends 'main.html' %}
{% load static %}

{% block content %}
<style>

.bg-danger{
     background: linear-gradient(to left, #cc0000 30%, #ffffff 125%) !important;
}
.bg-primary {
    background: linear-gradient(to right, #373b44, #4286f4) !important;
}
.bg-cherry{
    background: linear-gradient(to right, #493240, #f09) !important;
}
.card {
    background-color: #fff;
    border-radius: 10px;
    border: none;
    position: relative;
    margin-bottom: 30px;
    box-shadow: 0 0.46875rem 2.1875rem rgba(90,97,105,0.1), 0 0.9375rem 1.40625rem rgba(90,97,105,0.1), 0 0.25rem 0.53125rem rgba(90,97,105,0.12), 0 0.125rem 0.1875rem rgba(90,97,105,0.1);
}
#heroimage{
    background-image: url("/static/images/usedcarspage/showroomvan.jpg");
    padding-top: 200px;
    background-size: cover;
    padding-bottom: 165px;
}
.bg-darkblue{
    background: linear-gradient(to left, #003366 0%, #ccffff 100%) !important;
}
</style>
<!-- <div class="row" style="height:85px; background-color:black"></div> -->

<!-- Search Section -->
<div class="" id="heroimage">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <form>
                <div class="input-group">
                    <input type="text" name="q" class="form-control form-control-lg" placeholder="Search for vans" />
                </div>
                <div class="input-group-append justify-content-center">
                    <button class="btn btn-info " type="submit" id="button-addon2">Search</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="container-fluid mt-4">
    <div class="row m-2">
        <div class="col-md-8">
            <div class="card w-100">
                <div class="card-header bg-cherry text-white">
                    <h4 class="card-title">Used Vans</h4>
                </div>
                <div class="card-body">
                    Sorry, we don't have any vehicles available at the moment, please call back another time as we always have stock coming in.
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card w-100 radius-15 bg-primary">
                <div class="card-body text-center">
                    <div class="p-4 radius-15">
                        <img src="https://bootdey.com/img/Content/avatar/avatar1.png" width="110" height="110" class="rounded-circle shadow p-1 bg-white" alt="">
                        <h5 class="mb-0 mt-5 text-white">Used car showroom</h5>
                        <p class="mb-3 text-white">Contact Us</p>
                        <h5 class="mb-2 mt-2 text-white"><i class="fas fa-mobile-alt mr-3" ></i>07765 244907</h5>
                        <h5 class="mb-2 mt-2 text-white"><i class="fas fa-phone mr-3" ></i>0121 5724898</h5>
                        <div class="d-grid"><a href="#" class="btn btn-white radius-15">FIND US</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row m-2">
        <div class="col">
            <div class="card w-100">
                <div class="card-header bg-darkblue">
                    <h5 class="card-title m-2">Used Vans for sale</h5>
                </div>
                <div class="card-body">
                    <p class="card-text">
                        We are confident you will not be disappointed with our selection of quality used vans. At Used Car Showroom Ltd we offer an extensive range of services and extras meaning that you can buy your used van with confidence and peace of mind. Our showroom in Smethwick stocks a wide range of vans that are ready for viewing today.
                    </p>
                </div>
            </div>
        </div>
    </div> 
</div>
<div class="row m-2">
    <dic class="col">
        <div class="card w-100">
            <div class="card-header bg-dark text-white">
                <h6 class="card-title m-2"><i class="fas fa-map-marker-alt mr-2" ></i>Unit 13 CORNWALL ROAD INDUSTRIAL ESTATE, Smethwick, West Midlands, B66 2JT<span class="float-right"><i class="fas fa-phone-alt mr-2" ></i>07765 244907 | 0121 5724898</span></h6>
            </div>
        </div>
    </dic>
</div>
{% endblock content %}